### ISSUE TITLE
J'ai une erreur sur l'installation de la version 6.0.0.0

### ISSUE THREAD

**Issue by lmag** [Evarisk/WP-Digirisk#1]
Bonjour,
J'ai une erreur sur l'installation : 
PHP Fatal error:  Cannot redeclare class wpdigi_societies_mdl in /var/www/XXXXX/wp-content/plugins/evarisk/modules/societies/model/wpdigi_societies_mdl.php on line 15, referer:

**Comment by eoxia-alexandre** [comment]
Bonjour,

Cette erreur est due à la présence du plugin Evarisk version 5. Pour ne pas avoir cette erreur, il vous faut désactiver le plugin Evarisk avant l'activation de Digirisk.

Cdlt,
