### ISSUE TITLE
Bug d'affichage lors de cotation des risques

### ISSUE THREAD

**Issue by ghost** [Evarisk/WP-Digirisk#10]
Bonjour,

Lorsque je veux ajouter un nouveau risque et faire sa cotation l'affichage bug. 
Je joins une capture d'écran.

Merci d'avance,

faurmic
![capture d ecran 2016-11-18 a 09 20 38](https://cloud.githubusercontent.com/assets/23644724/20504659/b7f8d8a6-afec-11e6-98ef-fd03b1b8a7eb.png)

**Comment by lmag** [comment]
Bonjour,

Dans les outils de WordPress vous avez Digirisk et un bouton vert marqué "Résoudre" pouvez vous cliquez dessus ?

Cdlt
Laurent

**Comment by ghost** [comment]
Bonjour Laurent,

Merci pour votre mail.
J'ai cliqué sur résoudre via le menu outils de Wordpress.
Aucun changement.

Cordialement,

Michaël

2016-11-21 14:03 GMT-10:00 Laurent Magnin notifications@github.com:

**Comment by eoxia-jimmy** [comment]
Bonjour, pour compléter la réponse de Laurent,

Dans l'interface "Digirisk outils" (que vous êtes allez précédemment), vous devez aller dans l'onglet "Correction de la méthode d'évaluation Evarisk". Et la cliquer sur "Réinitialiser".

**Comment by ghost** [comment]
Bonjour,

Merci beaucoup ça fonctionne!

Cordialement,

Michaël

2016-11-22 22:12 GMT-10:00 eoxia-jimmy <notifications@github.com>:

**Comment by lmag** [comment]
Super bonne évaluation des risques et n'hésitez pas à nous joindre, je clos le ticket
PS : on devrait publier une MAJ intéressante milieu de semaine prochaine...
