### ISSUE TITLE
Ajout nouveau risque

### ISSUE THREAD

**Issue by ValvePF** [Evarisk/WP-Digirisk#11]
Bonjour,

Nous avons depuis quelques semaines travailler sur la refonte de notre document unique. Nous utilisons la version 6.2.1.2.
Lorsque nous utilisions l'ancienne version (5.1.9.5) nous pouvions créer des nouveaux risques avec des logos de risques que nous pouvions choisir et non pas ceux de la liste. 

Comment pouvons nous faire dans la nouvelle version pour créer des risques propres à notre entreprise qui ne figure pas dans la liste existante dans digirisk ?

Merci d'avance,
Lucie

**Comment by eoxia-alexandre** [comment]
Bonjour,

Dans la version 6 de DigiRIsk il n'est actuellement pas possible de modifier la liste des risques existants pour en ajouter ou en supprimer. Il n'est pas non plus prévu (pour le moment) d'intégrer cette possibilité

Cdlt,
Alexandre

**Comment by ValvePF** [comment]
Bonjour, 

Je vous remercie pour votre réponse 

Lucie

**Comment by lmag** [comment]
Re-bonjour,

En effet, nous avons souhaité conserver uniquement les catégories de risque de l'INRS qui sont expliqués dans le document ed840.pdf.
Si vous ne trouvez pas votre bonheur vous avez toujours la catégorie autres.
Cela vous permet de simplifier l'évaluation des risques et d'être sur un base commune et de profiter des support de formation gratuit de l'INRS. :)
