### ISSUE TITLE
erreur lorsqu'il manque la signature d'un participant dans les causerie

### ISSUE THREAD

**Issue by Remi-tz** [Evarisk/WP-Digirisk#113]
**Reproduire le bug**
Étapes pour reproduire le comportement indésiré :
1. Aller à '....'
2. Cliquer sur '....'
3. Voir l'erreur '{"errors":{"eo_model_invalid_type":["digi\\Sheet_Causerie_Intervention_Model => formateurSignature: Pas d'image d\u00e9finie(string) is not a array"]},"error_data":[]}'

**Comportement attendu**
Description du comportement souhaité.

**Captures d'écrans**
Si possible, ajoutez des captures d'écran pour nous aidez à identifier le problème.
![Screenshot](https://user-images.githubusercontent.com/61967469/77551827-12183880-6eb3-11ea-9c69-dd3ce433f032.png)

bouton imprimer manquant

**Comment by mpvernadat** [comment]
Je confirme nous avons exactement le même bug
