### ISSUE TITLE
Erreur lors de la validation de la causerie à la dernière étape

### ISSUE THREAD

**Issue by mpvernadat** [Evarisk/WP-Digirisk#115]
**Description du problème**
Lors de la validation à la dernière étape on a une erreur et le fichier *.odt n'est pas généré

**Reproduire le bug**
Étapes pour reproduire le comportement indésiré :
1. Aller à 'derniere etape d'une causerie'
2. Cliquer sur 'valider'
3. Voir l'erreur '{"errors":{"eo_model_invalid_type":["digi\Sheet_Causerie_Intervention_Model => formateurSignature: Pas d'image d\u00e9finie(string) is not a array"]},"error_data":[]}'

**Comportement attendu**
Description du comportement souhaité.

**Captures d'écrans**
Si possible, ajoutez des captures d'écran pour nous aidez à identifier le problème.

**Configuration ordinateur (Merci de compléter les informations suivantes) :**

**Configuration téléphone (Merci de compléter les informations suivantes) :**

**Divers**
Rajouter tout ce qui peut nous permettre de corriger le problème.

**Comment by lmag** [comment]
Ce point est corrigé sur votre instance

**Comment by eoxia-jimmy** [comment]
Doublon avec #113

**Comment by lmag** [comment]
Ok pour moi
