### ISSUE TITLE
Affichage de Task Manager et les causeries on affiche l'ancienne interface

### ISSUE THREAD

**Issue by lmag** [Evarisk/WP-Digirisk#116]
**Description du problème**
Affichage de Task Manager et les causeries on affiche l'ancienne interface

**Comment by nicolas-eoxia** [comment]
![image](https://user-images.githubusercontent.com/52404047/78875593-6b08d480-7a4e-11ea-8baf-e56b53d682a4.png)

**Comment by lmag** [comment]
Super
