### ISSUE TITLE
[DEMANDE D'AMELIORATION] Saisie unique des dates d'affectation

### ISSUE THREAD

**Issue by Marc-AntoineHADDAD** [Evarisk/WP-Digirisk#12]
Bonjour à toute l'équipe,

Dans vos spec à venir, serait-il possible de faire apparaître de nouveau les dates d'embauche ou d'affectation dans l'entreprise au niveau des profils utilisateurs. Cela éviterait de procéder à des saisies multiples sur chaque unité de travail.

Merci d'avance,

Bien à vous,

Marc-Antoine

**Comment by lmag** [comment]
Bonjour,

Les dates d'embauches avait été mis en place pour la pénibilité notamment pour l'impression de la fiche du décret. Vu les modifications du décret, la fiche étant maintenant sortie par les logiciels de paye, nous n'avons pas prévue de la remettre sur les personnels pour le moment. Les anciennes informations sont toujours dans la base, nous analyserons ce point lorsque nous attaquerons le coté personnel.

Bien cordialement
Laurent

**Comment by lmag** [comment]
Ce point est supprimé :) les nouvelles fiches sont en place dans la nouvelle Version 6.2.5.2
