### ISSUE TITLE
encodage accent

### ISSUE THREAD

**Issue by lmag** [Evarisk/WP-Digirisk#128]
**Description du problème**
erreur impression fiche UT si la photo contient un accent
![image](https://user-images.githubusercontent.com/3288514/79454722-03253180-7fec-11ea-8141-4e3e0eadc412.png)

**Comment by evarisk-theo** [comment]
Fixé dans la 7.6.0

**Comment by lmag** [comment]
KO

**Comment by evarisk-theo** [comment]
Re-fixé dans la 7.6.0
