### ISSUE TITLE
Gestion des droits

### ISSUE THREAD

**Issue by thomasmaitre1** [Evarisk/WP-Digirisk#134]
**Description du problème**

Problème d'attribution de droit, la catégorie auteur sur DigiRisk donne tout les droits sans possibilité de modifier, et de les restreindre.  Il était question de permettre à un employé de réaliser des plan de prévention, mais pas de modifier le DUER.

**Comportement attendu**

L'onglet auteur ne devrait ouvrir que les droits liés à la réalisation des plans de prévention, et non pas ouvrir l'accès pour modifier le DUER. 

.

Configuration ordinateur
 - OS: NC
 - Browser Edge
 - Version NC

**Comment by evarisk-theo** [comment]
Après test avec @thomasmaitre1 , le bug semble être résolu
