### ISSUE TITLE
Perte d'interface de quantification du risque suite migration

### ISSUE THREAD

**Issue by FKACAPIC29** [Evarisk/WP-Digirisk#14]
Bonjour,
Je vous prie de trouver ci-dessous les éléments du problème tels que je les ai rencontrés suite à une migration d'EVARISK vers DIGIRISK.

DIGIRISK 6.2.3.0
La version actuelle FIREFOX est 50.1.0 sans aucun module spécifique.

Impossible de quantifier le risque car la fenêtre qui s'ouvre n'affiche que le tableau mais sans aucun texte ni possibilité de sélection.
[extensions.docx](https://github.com/Evarisk/Digirisk/files/689905/extensions.docx)
[vue détail des risques.docx](https://github.com/Evarisk/Digirisk/files/689904/vue.detail.des.risques.docx)
[vue unité de travail.docx](https://github.com/Evarisk/Digirisk/files/689903/vue.unite.de.travail.docx)

**Comment by lmag** [comment]
Bonsoir,

Vous trouverez dans le menu Outils de WordPress>DigiRisk
Vous avez un outils de réparation et de controle pouvez vous cliquer sur l'onglet "correction de la méthode d'evaluation"
Et nous dire si le problème est résolu.

Bien cordialement

**Comment by FKACAPIC29** [comment]
Bonjour,
Bonne nouvelle, cela à fonctionner. Par contre lors de l'ouverture de la vue pour la cotation, cette dernière prend la totalité de l'écran et il manque peut être les titres des lignes et colonnes. 
[cotation_risque.docx](https://github.com/Evarisk/Digirisk/files/693350/cotation_risque.docx)

Il faut rappeler que je suis en mode correction à ce stade.

On avance, :-)

**Comment by FKACAPIC29** [comment]
Bonjour,
Bonne nouvelle, cela à fonctionner. Par contre lors de l'ouverture de la vue pour la cotation, cette dernière prend la totalité de l'écran et il manque peut être les titres des lignes et colonnes.
cotation_risque.docx

Il faut rappeler que je suis en mode correction à ce stade.

On avance, :-)

**Comment by lmag** [comment]
Oups, votre écran est trop petit, on ne gère pas bien les tailles d'écrans à ce jour. Nous prévoyons une mise en production fin janvier d'une nouvelle version avec des CSS entièrement revus cela réglera ce problème.
Je ne vois qu'une solution augmenter la résolution de l'écran ou réduire le zoom du navigateur.
Désolé...

**Comment by lmag** [comment]
Dans cette nouvelle version les écrans sont pris en charge jusqu'a une taille 1024 (pour les rétro projecteurs).
Nous travaillerons bientot sur les petits écrans notamment pour les téléphones
