### ISSUE TITLE
[BUG] simple détail à régler facilement

### ISSUE THREAD

**Issue by TLSB** [Evarisk/WP-Digirisk#142]
**Description du problème**
Faute de saisie sur l'intitulé du risque - "Risques de trébuchement, heurt ou autre pertubation du mouvement" - il manque un "r" à "perturbation"

**Comportement attendu**
Correction lors de la prochaine mise à jour

Merci ( première utilisation autonome de github :):)  )

**Comment by lmag** [comment]
Merci pour la première contribution, je l'ai noté pour la prochaine mise à jour

**Comment by lmag** [comment]
Pour information la gestion des corrections, fautes etc... devrait un jour ce faire dans WordPress...
https://translate.wordpress.org/projects/wp-plugins/digirisk/dev/fr/default/
C'est intéressant à savoir bien que nous n'ayons pas encore fini la préparation de la traduction....

**Comment by evarisk-theo** [comment]
Corrigé dans la 7.6.0
