### ISSUE TITLE
Manque les informations sur l'affichage légal

### ISSUE THREAD

**Issue by lmag** [Evarisk/WP-Digirisk#143]
**Description du problème**
Les informations de l'affichage légal ne sont pas reprise

**Reproduire le bug**
Étapes pour reproduire le comportement indésiré :
1. Remplir les informations
2. Imprimer une affiche légale et diffusion d'information
3. Vérifier l'impression

![image](https://user-images.githubusercontent.com/3288514/85030678-0b315700-b17e-11ea-90a9-d8b89b3b8d54.png)

**Comment by lmag** [comment]
à tester sur demo

**Comment by evarisk-theo** [comment]
non reproductible sur demo
