### ISSUE TITLE
Obligation de remplir l'adresse postale pour les groupements et unités de travail

### ISSUE THREAD

**Issue by FKACAPIC29** [Evarisk/WP-Digirisk#15]
Bonjour,
Je souhaiterai vous soumettre un autre point qui m'ennuie quelque peu dans le renseignement des groupement et unités de travail.
En effet, sauf à laisser un blanc qui ressort de façon impropre lors de la génération du DUER.
Il faudrait introduire la notion de mono-site ou  de multi-sites lors de la configuration.
Je précise ma pensée...
Dans le cas d'un mono-site de production, le groupement principale reprend l'adresse postale.
Par contre les sous-groupements et unités de travail devraient pouvoir recevoir les données propre en interne ou aucune si besoin.
Ceci apporterait de la clarté lors de la génération.  

A lire votre point de vue,

**Comment by lmag** [comment]
Bonjour,

Pour le coup, ce point la est parfaitement bien géré. 
1) Le vrai multisite est géré avec une WordPress MU (gestion native) avec une duplication de site modèle en natif ( Société avec holding et filiales)
2) Le "faux" multisite est géré avec les groupements (1 société avec Société, Services administratifs, Services de production etc...)
3) La société simple Directement les unités...

Pour cela je vous conseil si vous avez des doutes de prendre 1 heures de formation sur notre site :) 

Cordialement
