### ISSUE TITLE
Bug visualisation des pièces jointes

### ISSUE THREAD

**Issue by ylseagle** [Evarisk/WP-Digirisk#151]
Bonjour,

Après avoir attaché une pièce jointe (.odt, .jpg, .pdf, ...) à un "Accident" par exemple, il est impossible de visualiser ou de télécharger ladite pièce jointe (cf. capture ci-dessous).
![Capture](https://user-images.githubusercontent.com/61774131/85947560-80f6a900-b95c-11ea-9c3f-3d931e0eca52.JPG)

Nous rencontrons le problème aussi bien sur le site de démo et également sur notre serveur interne.

**Comment by ylseagle** [comment]
Quelqu'un a t-il une solution à ce problème ?

**Comment by lmag** [comment]
Bonjour
Effectivement le bug est reproductible sur la démo : https://demo.digirisk.com/
Nous allons voir à le planifier au plus tôt

**Comment by lmag** [comment]
La gestion de la partie Arret de travail tombe dans la partie RGPD... Cela rends donc le sujet plus complexe.
Je propose afin de le simplifier dans DigiRisk de supprimer l'upload (afin de ne pas avoir a gérer les fichiers)
De rajouter un lien hypertexte en face de champ arret de travail vers le fichier de votre choix
Pour rappel les durées de conservations de éléments sont ici :
https://www.cnil.fr/fr/declaration/ru-041-gestion-des-accidents-du-travail-et-maladies-professionnelles-par-lassurance#:~:text=Dur%C3%A9e%20de%20conservation%20des%20donn%C3%A9es&text=2%C2%B0%20Cinq%20ans%20apr%C3%A8s,travail%20ou%20une%20maladie%20professionnelle.
