### ISSUE TITLE
[BUG] gestion des droits

### ISSUE THREAD

**Issue by lmag** [Evarisk/WP-Digirisk#157]
**Description du problème**
Une description claire et concise.

![image](https://user-images.githubusercontent.com/3288514/87886671-4d6ce300-ca1f-11ea-8128-47707891c37e.png)

**Reproduire le bug**
Étapes pour reproduire le comportement indésiré :
Création d'un nouveau user

**Comportement attendu**
pas de droit

**Comment by evarisk-theo** [comment]
Après test avec Thomas, ce bug semble résolu
