### ISSUE TITLE
Date d'embauche

### ISSUE THREAD

**Issue by JCBourdel** [Evarisk/WP-Digirisk#17]
Bonjour,
Je rejoins la demande ci dessous pour une prise en compte d'un champ supplémentaire "Date d'embauche" lors de la création d'un profil.
C'est assez perturbant de voir ce champ dans la liste des évaluateurs, pour lequel après modification du champ date, l'info n'est pas sauvegardé. Finalement autant le supprimer si il est d'aucune utilité.

Cdt,
Bourdel JC

![2017-01-26_173730](https://cloud.githubusercontent.com/assets/21120570/22340609/4ab32310-e3ee-11e6-9274-9bd421cc0225.png)

**Comment by lmag** [comment]
C'est noté sous le numéro de ticket 6886 nous supprimerons le champs lors d'une prochaine livraison.

**Comment by eoxia-jimmy** [comment]
Bonjour,

Dans la mise à jour 6.2.5.2, la date d'embauche est supprimée.

Cordialement,
Jimmy.
