### ISSUE TITLE
[GESTION DES RISQUES]Confusion sur la matérialisation du risque routier

### ISSUE THREAD

**Issue by Marc-AntoineHADDAD** [Evarisk/WP-Digirisk#24]
Bonjour à tous,

Suite à la mise à jour du plug-in, j'ai constaté que l'icône de signalisation du risque routier a été intervertie avec le risque relatif aux circulations internes.
Je vous félicite également pour cette mise à jour qui rajoute de l'ergonomie et de la visibilité au plug-in

Bien à vous,

Marc-Antoine HADDAD

**Comment by lmag** [comment]
Nous regarderons ce point porte le numéro 8975.
Cela sera fait dans le module de mise à jour vous pourrez retrouver le numéro de ticket sur WordPress 
https://fr.wordpress.org/plugins/digirisk/
Cordialement

**Comment by lmag** [comment]
Cette inversion à été corrigée dans la version 6.2.10.0
