### ISSUE TITLE
Point correctif

### ISSUE THREAD

**Issue by laurentroger** [Evarisk/WP-Digirisk#31]
Bonjour,

J'utilise la version 6.3.2 de digirisk avec Task Manager 1.4.2 sur un WP 4.8.2, j'ai remarqué que lors de la création/edition d'une tâche corrective rattachée à un groupement que le point correctif n'est pas pris en compte => le champ "comment_content" associé restant vide dans la base SQL.

![1_sql](https://user-images.githubusercontent.com/33020208/31877983-ccd49414-b7d8-11e7-9b28-085775518c66.png)
![1_web](https://user-images.githubusercontent.com/33020208/31877984-ccf99520-b7d8-11e7-95da-2b2fb85b7373.png)
![2_creation_du_point](https://user-images.githubusercontent.com/33020208/31877985-cd37f3ce-b7d8-11e7-91a9-737bacf3c018.png)
![3_sql](https://user-images.githubusercontent.com/33020208/31877986-cd72fbf4-b7d8-11e7-9841-91ed78426747.png)
![3_web](https://user-images.githubusercontent.com/33020208/31877987-cdf4f9b0-b7d8-11e7-8d34-3a8bb05dcdb4.png)
![4_edition_du_point_mais_non_present](https://user-images.githubusercontent.com/33020208/31877989-ce4ad5ec-b7d8-11e7-8d16-47d193d8813d.png)

Lors de la création du point correctif à l'aide de task manager, je peux valider avec "ok" lorsque que je souhaite le consulter il n'apparait pas, en eregardant dans la table SQL (capt 3_sql), on voit que les commentaires sont pris en compte mais pas les point correctif. D'où cela peut-il provenir ?

Merci

**Comment by eoxia-jimmy** [comment]
Bonjour,

La mise à jour 6.3.3 de DigiRisk et la 1.4.3 de Task Manager corrige ce problème.

Il se peut que vous ayez plusieurs tâches affectées à un risque, dans ce cas la il vas falloir supprimer les doublons.

Cordialement, Jimmy L.

**Comment by eoxia-jimmy** [comment]
Bonjour,

Est-ce que le problème est résolu ?

Cordialement, Jimmy L.

**Comment by laurentroger** [comment]
Bonjour,

Je vous remercie, je viens de tester à l'instant et les points s'affiche
correctement après édition avec Task Manager.

Cdlt

--
LR
