### ISSUE TITLE
Parse error suite à la mise à jour

### ISSUE THREAD

**Issue by FKACAPIC29** [Evarisk/WP-Digirisk#38]
Bonjour,
Suite à la mise à jour des extensions DIGIRISK + TASK MANAGER j'obtiens le message suivant : 
**Parse error: syntax error, unexpected '[' in C:\EvariskServer\htdocs\Evarisk\wp-content\plugins\digirisk
\modules\accident\action\accident.action.php on line 76**

**Comment by eoxia-jimmy** [comment]
Bonjour,

en attendant la prochaine mise à jour 6.5.0 qui vas résoudre ce problème, vous pouvez désactiver le module "Accident" de Digirisk.

## Solution 1: Désactiver le module "Accident".

Pour cela, rendez vous dans le fichier "modules/accident/accident.config.json" et passer la valeur de "state" à false.

Si vous n'avez **pas** l'index "state", vous pouvez le rajouter à la fin du fichier comme suit:

```JSON
{
	"name": "Accident",
	"slug": "accident",
	"version": "6.5.0",
	"description": "Le module gérant les accidents",
	"path": "modules/accident/",
	"dependencies": {
		"filter": {},
		"action": {},
		"helper": {},
		"shortcode": {},
		"model": {},
		"class": {}
	},
	"state": false
}
```

PHP < 5.4 ne connaissant pas cette syntaxe, il provoque cette fatal error.

## Solution 2: Mettre à jour votre version PHP

Nous recommandons la >= 5.6.x.

Cordialement,
Jimmy L.

**Comment by eoxia-jimmy** [comment]
La version 6.5.0 corrige l'erreur PHP.

Je ferme l'issue
