### ISSUE TITLE
Sauvegarde DIGIRISK

### ISSUE THREAD

**Issue by doudoufly** [Evarisk/WP-Digirisk#39]
Bonjour,
Je voulais savoir si la sauvegarde de la base de donnée WordPress avec phpmyadmin est suffisante pour sauvegarder DIGIRISK ou faut faire d'autres manipulations ?
A+

**Comment by eoxia-jimmy** [comment]
Bonjour,

Pour faire une sauvegarde de votre DigiRisk une exportation de la base de donnée + le contenu de dossier upload de wp-content de votre WordPress.

**Comment by doudoufly** [comment]
Bonjour,
Pouvez-vous me dire selon les photos si je dois sauvegarder tout la base de donnée wp (wordpress) ou autres ?
