### ISSUE TITLE
[DENOMINATION RISQUES] Correction orthographe de certains risques

### ISSUE THREAD

**Issue by Marc-AntoineHADDAD** [Evarisk/WP-Digirisk#5]
Bonjour,

Certaines dénominations de risques ont vu des coquilles s'y glisser : 
- Incendie/Explosion : Est marqué explostion dans le logiciel
- Electricité : il manque un accent sur le e

Je sais qu'il s'agit là de corrections mineures, mais cela créé des fautes lors de la génération du DUER et rallonge de fait la correction orthographique.

Bien à vous,
Marc-Antoine HADDAD

**Comment by eoxia-jimmy** [comment]
Bonjour,

Même si c'est des corrections mineures, c'est important de les corriger! 
Merci de les avoir reportées, ce sera corrigé dans la version 5.1.5.6.

Bonne journée.

**Comment by lmag** [comment]
Merci bien pour les corrections Jimmy pour vos poster le numéro de tracking :) de [Task Manager](https://fr.wordpress.org/plugins/task-manager/)

**Comment by eoxia-jimmy** [comment]
Bonjour,

le numéro de tracking: #4833 Correction orthographique.

Bonne journée.

**Comment by lmag** [comment]
Bonsoir,

Vous pouvez retrouver la correction qui a été livrée ici :
https://fr.wordpress.org/plugins/digirisk/changelog/ 👍 
Merci pour votre aide
