### ISSUE TITLE
Mise a jour de 6.6.1 vers 6.6.3 bug avec Task Manager

### ISSUE THREAD

**Issue by Marsou01** [Evarisk/WP-Digirisk#51]
Bonjour,

Lorsque je fais la mise à jour de Digirisk de la version 6.6.1 vers la version 6.6.3.
L'extension Task Manager provoque un bug qui bloque complètement WP.
J'utilise la version 1.5.1 de Task Manager.

Y a t il des recommandations version pour Task Manager pour éviter le plantage ?
Merci

**Comment by eoxia-jimmy** [comment]
Bonjour, nous allons faire une mise à jour de DigiRisk ainsi que de Task Manager pour corriger ce conflit. 

Pour le moment, il faut malheureusement désactiver Task Manager.

**Comment by lmag** [comment]
La mise à jour vers la version 7.0.1 devrait corriger ce point

**Comment by hmel50100** [comment]
Bonjour,
J'ai la version 7.0.1 de Digirisk et la version 1.7.0 de Task-manager, et le problème persiste, 

Quand j'active Digirisk, le plugin Task-Manager se desactive automatiquement. et a l'inverse quand j'active le plugin Digirix et activer en premier et que j'active ensuite Task-Manager, Task manager ne s'active jamais.

Y à t'il une mise à jours prévu prochainement ?

**Comment by lmag** [comment]
Pouvez vous nous en dire un peu plus sur votre installation est ce en local ?
La version php

**Comment by hmel50100** [comment]
Bonjour
J'ai installer le logiciel sur mon wamp.

J'ai essayer avec PHP 5.6.38 / 7.0.32 / 7.1.22 / 7.2.10 / 7.2.12

en ayant les version Digirisk 6.4.3 - 7.0.1

task manager 1.5.0 / 1.6.0 / 1.7.0

Impossible de charger les 2 plugin digirisk et task manager

quand j'ai le plugin digirisk activé et que j'éssai d'activer TaskManager
dans les version < 1.7.0 j'ai un message qui s'affiche :

L’extension n’a pas pu être activée, car elle a déclenché une *erreur
fatale*.:

File
C:\wamp64\www\wordpress\wp-content\plugins\task-manager/module/liaison-post-type/liaison-post-type.config.json
is not found



alors que si j'active que Task Manager sans digirisk, Task manager
fonctionne parfaitement.

**Comment by eoxia-jimmy** [comment]
Bonjour 

Peut être cette solution:

Dans le fichier "C:/wamp64/www/wordpress/wp-content/plugins/task-manager/task-manager.config.json", enlever la ligne "module/liaison-post-type/liaison-post-type.config.json" dans le tableau "modules".

Puis réactiver Task Manager.

**Comment by hmel50100** [comment]
Bonjour, 
Dans la dernière version de Taskmanager cette ligne n'est pas dans le fichier JSON. 

J'ai reinstaller la version 1.6.0 de Task manager la ligne existe mais toujours une erreur mais pas la même

![2018-12-12_19h08_35](https://user-images.githubusercontent.com/8049218/49889363-94f1bd00-fe41-11e8-85e1-7f80a8705639.png)

**Comment by hmel50100** [comment]
J'ai supprimer la ligne correspondant à shortcode-help.config.json
du coup je n'ai plus d'erreur. un message m'indique extension activié mais elle n'est pas activée dans la liste de plugin. 

![2018-12-12_19h13_22](https://user-images.githubusercontent.com/8049218/49889524-0467ac80-fe42-11e8-93ba-f28c9fad2b58.png)

**Comment by eoxia-jimmy** [comment]
Vous rencontrez l'erreur "C:\wamp64\www\wordpress\wp-content\plugins\task-manager/module/liaison-post-type/liaison-post-type.config.json
is not found" même avec la version 1.7.0 ?

Ou est-ce une autre erreur ?

**Comment by hmel50100** [comment]
Dans la version 1.7.0 de Task-manager avec Digirisk 7.0.2, j'ai le même problème que mon dernier message. 
J'ai un message "extension activée" mais Task manager reste inlassablement désactivé. 

Par contre dans le cas de la version 1.6.0 et 1.7.0 si je desactive le plugin digirisk, Task manager s'active normalement et fonctionne parfaitement mais je n'ai plus digirisk ... 

Je remarque que sur votre site de test, les deux plugins fonctionne parfaitement. Quels sont les versions qui sont utilisé sur votre serveur ?

Est-ce que l'erreur ne viendrais pas du fait que je soit sur un wamp local et pas sur un serveur en ligne?

**Comment by hmel50100** [comment]
Bonjour imag, 
comme vous avez clôturer le sujet, je supose que vous avez trouver la solution. j'aimerais donc la connaitre  si non il faut laisser le post ouvert !
