### ISSUE TITLE
Problème de mise à jour des données version 7

### ISSUE THREAD

**Issue by Marc-AntoineHADDAD** [Evarisk/WP-Digirisk#53]
Lors de la mise à jour du plugin version 7, j'ai lancé une mise à jour des données digirisk, mais cette dernière ne s'exécute pas et ne me permet pas d'utiliser le plugin

**Comment by eoxia-jimmy** [comment]
Pouvez vous essayer de rafraîchir le cache de votre navigateur avant d'atteindre la page de mise à jour ?

https://fr.wikipedia.org/wiki/Aide:Purge_du_cache_du_navigateur

**Comment by Marc-AntoineHADDAD** [comment]
Super, ça fonctionne, merci beaucoup. Avant de clôturer le ticket, est-ce que vous avez l'intention de continuer à développer l'outil the EPI? ce plugin m'aide beaucoup mais ne fonctionne pas correctement sur la dernière version de WP.
Bien à vous,
Marc-Antoine

**Comment by lmag** [comment]
Bonjour,

La mise à jour de la nouvelle version pour la gestion de EPI à été envoyée ce matin...
Oui ce plugin est toujours maintenu, on l'utilise en interne :)
