### ISSUE TITLE
Gestion des rôles et de droits

### ISSUE THREAD

**Issue by lmag** [Evarisk/WP-Digirisk#54]
Question client :
Nous avons 6 rôles dans les profils utilisateurs de la plateforme :
- Superadministrateur/administration pour supprimer et créer les sites
- Abonné pour lire
- Contributeur pour associer des commentaires
- Auteur pour apporter de nouvelles pages, articles
- Editeur pour publier les pages

En regard de l'extension Digirisk, nous souhaiterions établir :
- un mode lecture de Digirisk sans possibilité de commenter, de modifier les risques, les cotations
- un mode commentaire de Digirisk sur une cotation sans possibilité de modifier, les risques, les cotations
- un mode auteur d'un nouveau risque sans possibilité de publier
- le mode éditeur conservant la fonctionnalité actuelle de manage Digirisk

Qu'en pensez-vous ?

**Comment by lmag** [comment]
Nous avons vos propositions pour le moment le niveau de détails et le suivant  :
https://www.evarisk.com/document-unique-logiciel/documentation/utilisateurs/
Abonné : Il peut gérer que son profil. Il ne voit pas DigiRisk.
Contributeur : Lecture et écriture + Droit à DigiRisk sauf pour les médias
Auteur : Lecture et écriture + Droit à DigiRisk
Éditeur : Accès à tout (réglages, outils, comme admin)
Le fait de paramétrer les rôles avec l'extension "user role editor" est très intéressant et doit être manipuler avec précaution.
A ce jour dans notre planning, nous n'avons pas encore prévu d’accès en lecture simple au Document Unique sauf l'impression native au format libreoffice.

**Comment by toucan001** [comment]
Bonjour,
Le besoin est à 2 niveaux l'opérateur au poste et le gestionnaire Sécurité atelier (ou le gestionnaire Sécurité site). L'opérateur doit avoir un accés rapide à l'information de son poste par Digirisk(Volet site internet) et déposer une détection d'incident. Au contraire, le responsable sécurité doit pouvoir lui répondre et modifier la cotation du risque.
