### ISSUE TITLE
Maj bloqué sur un Multisite pour le passage de la version 6.6.3 vers la 7.0.1

### ISSUE THREAD

**Issue by Estelleclairemidi** [Evarisk/WP-Digirisk#56]
Bonjour,

La mise à jour ne semble pas ce lancer.
Pourriez vous regarder.

Merci

**Comment by lmag** [comment]
Bonjour,

Effectivement nous avons noté ce "bug" de lancement du script de mise à jour, il suffit de faire CTRL+F5 afin de vider le cache de votre navigateur. La mise à jour ce lancera automatiquement

Laurent
