### ISSUE TITLE
Commentaires risques

### ISSUE THREAD

**Issue by ELssr01** [Evarisk/WP-Digirisk#59]
Lorsque l'on rentre un commentaire assez long sur un risque, une barre pour faire défiler le texte apparait, et nous empêche de voir le texte que l'on écrit.

![digirisk_comm](https://user-images.githubusercontent.com/45351153/49005093-2258c000-f166-11e8-9006-e6f4f3ae268e.PNG)

**Comment by lmag** [comment]
Bonsoir,
Effectivement c'est un problème. Nous allons y réfléchir voir ce que nous faisons...
Si vous avez une idée n'hésitez pas ...

**Comment by eoxia-jimmy** [comment]
Corrigé dans la 7.1.0
