### ISSUE TITLE
[DEMANDE D'AMELIORATION]Demandes diverses

### ISSUE THREAD

**Issue by Marc-AntoineHADDAD** [Evarisk/WP-Digirisk#6]
Bonjour,

Avez-vous prévu dans vos prochaines mises à jour de proposer des sélections entre les différents facteurs de risque, les mesures de prévention existantes et les mesures de prévention à mettre en place?
Par ailleurs, est-il également prévu de retrouver l'évolution du risque en fonction des évaluations (comme c'était le cas dans le plugin 5.)?

Bien à vous,

Marc-Antoine HADDAD

**Comment by lmag** [comment]
Bonsoir,

Je ne comprends pas bien votre première question ? Nous avons déjà les risques de l'INRS pour le moment nous resterons la dessus par défaut.
Pour les méthodes d'évaluations les 4 mises en place actuellement sont suffisante bien que l'on puisse en rajouter à l'infini.
Oui, nous allons le remettre pour le suivi de l'evaluation d'un risque, nous le gardons dans la base de donnée mais nous ne l'avons pas encore affiché...

Merci pour vos questions en espérant avoir bien répondu

**Comment by Marc-AntoineHADDAD** [comment]
Bonjour,

Merci pour votre prompt retour. Je clôture le ticket
