### ISSUE TITLE
Ajout d'utilisateur sans adresse mail

### ISSUE THREAD

**Issue by ELssr01** [Evarisk/WP-Digirisk#60]
On ne peut pas ajouter d'utilisateur sans adresse mail. Parfois, les employés n'ont pas d'adresse mail pour le travail, et mais on est quand-même obligé d'en écrire une pour pouvoir les mettre comme évaluateur sur leur unité de travail. Il serait bien de pouvoir ajouter un utilisateur sans adresse mail.

**Comment by lmag** [comment]
Par défaut, le mail est prenom.nom@demo.com c'est une obligation pour créer un compte sur WordPress
La creation rapide ce fait par le menu users 
utilisateurs digirisk
