### ISSUE TITLE
Titre GP

### ISSUE THREAD

**Issue by ELssr01** [Evarisk/WP-Digirisk#61]
Lorsque l'on veut changer le nom d'un GP, celui-ci s'écrit que en majuscule lorsque l'on écrit le titre, alors qu'en réalité une fois validé, le titre s'écrit bien en minuscule et majuscule.
![digirisk_titre](https://user-images.githubusercontent.com/45351153/49005198-63e96b00-f166-11e8-84d1-65326dd9f6e1.PNG)

**Comment by lmag** [comment]
Encore merci, c'est noté numero 24445

**Comment by eoxia-jimmy** [comment]
Corrigé dans la 7.1.0
