### ISSUE TITLE
Commentaires dans DU : Retour à la ligne 

### ISSUE THREAD

**Issue by ELssr01** [Evarisk/WP-Digirisk#62]
Lorsque l'on met 2 commentaires sur un même risque dans le DU global, il n'y a pas de retour à la ligne : c'est dommage ! Ce problème n'est visiblement pas présent dans les fiches de poste.
![digirisk_du_comm](https://user-images.githubusercontent.com/45351153/49026276-bf831b00-f19d-11e8-8bf9-cf53e6b39692.PNG)

**Comment by lmag** [comment]
Bonsoir,
Merci pour la remonté de ce bug c'est le numero 24444 il est planifié à la version 7.1.0
Merci

**Comment by eoxia-jimmy** [comment]
Corrigé dans la version 7.1.0
