### ISSUE TITLE
Le module .odt n'est pas pris en compte

### ISSUE THREAD

**Issue by toucan001** [Evarisk/WP-Digirisk#64]
Bonjour,
La gestion de du modèle .odt pour le fiches de poste n'est pas pris en compte lors de la génération d'une fiche de poste. Le problème semble identique pour le groupement, voir le DUER etc...

**Comment by lmag** [comment]
Bonjour,

C'est noté de notre coté dans votre backend sous le numero 1914

**Comment by eoxia-jimmy** [comment]
Bonjour,

le problème est résolu dans la version 7.1.0.

Attention à bien respecter la syntaxe dans vos modèles personnalisés.
