### ISSUE TITLE
utilisation sur plusieurs pc

### ISSUE THREAD

**Issue by Nath73** [Evarisk/WP-Digirisk#69]
Bonjour,
J'ai installé Evarisk en local sur mon pc (WordPress  est installé en mode classique, pas en multisite). Je souhaite pouvoir y accéder depuis un autre ordinateur de mon réseau d'entreprise, pour qu'une collègue puisse y collaborer. Comment faut-il procéder ? installer Evarisk sur le poste client et indiquer ds les paramètres de configuration système l'adresse IP du PC  serveur ? Ou bien modifier sur mon PC serveur "localhost" en l'adresse IP de mon ordinateur ? ou autrement...
Merci de votre aide
Nathalie

**Comment by lmag** [comment]
Bonjour
nous vous conseillons une installation sur une serveur.
Cependant ce guide pourra vous aider
https://youtu.be/Sy_f6wBGnjI
Bien cordialement 
Laurent
