### ISSUE TITLE
Affichage Actions correctives

### ISSUE THREAD

**Issue by Marsou01** [Evarisk/WP-Digirisk#7]
Bonjour,

Dans le Document Unique généré ODT, en fin de document (Plan d'action) les Actions correctives ne s'inscrivent pas dans la colonne correspondante du tableau.
La colonne Actions Correctives reste vide.
Est-ce normale où le champ de cette colonne n'est pas bon ?
![capture](https://cloud.githubusercontent.com/assets/14262445/19684938/5283775c-9aba-11e6-852c-c62482ee2bba.JPG)

**Comment by eoxia-jimmy** [comment]
Bonjour,

pour utiliser les actions correctives, il faut installer le plugin [Task Manager](https://fr.wordpress.org/plugins/task-manager/).
De plus ce champ sera opérationnel et rempli à la prochaine mise à jour de Task Manager qui sera disponible cette semaine.

**Comment by Marsou01** [comment]
Bonjour,

Merci pour l’information et votre réactivité.

Cordialement

Martial DAVID

Tel : +33(0) 9 88 9999 59

Natel : +33(0)6 64 16 59 54

De : eoxia-jimmy [mailto:notifications@github.com] 
Envoyé : mardi 25 octobre 2016 14:12
À : Evarisk/Digirisk Digirisk@noreply.github.com
Cc : Marsou01 martial77920@gmail.com; Author author@noreply.github.com
Objet : Re: [Evarisk/Digirisk] Affichage Actions correctives (#7)

Bonjour,

pour utilise les actions correctives, il faut installer le plugin Task Manager https://fr.wordpress.org/plugins/task-manager/ .
De plus ce champ sera opérationnel et rempli à la prochaine mise à jour de Task Manager qui sera disponible cette semaine.
