### ISSUE TITLE
Mise à jour vers 7.0.2 Plantage

### ISSUE THREAD

**Issue by FKACAPIC29** [Evarisk/WP-Digirisk#70]
Bonjour,
Je viens de connaitre un plantage lors de la mise à jour vers la version 7.0.2.
Tout s'est bien passé jusqu'à la version 6.6.3 puis lors de la mise à jour vers 7.0.2, le programme reste bloqué sur la mise à jour des DUER.
Avez-vous une solution pour reprendre la main ?

Bonne Année malgré tout.

**Comment by eoxia-jimmy** [comment]
Bonjour,

Pouvez vous essayer de vider le cache de votre navigateur ?

En général un CTRL + F5 est suffisant, sinon voici une procédure:

https://fr.wikipedia.org/wiki/Aide:Purge_du_cache_du_navigateur

Bonne année.

**Comment by FKACAPIC29** [comment]
Après vidage du cache le problème reste identique.
A moins qu'il faille attendre plus longtemps.
Le blocage est toujours présent lors de la phase de MISE A JOUR des DUER... La petite animation de roue qui tourne reste présente.  La base de données est conséquente également, y a-t-il un lien ?

**Comment by eoxia-jimmy** [comment]
Est-il possible d'avoir une partie (la plus récente) du contenu du fichier "error.log", se trouvant dans votre répertoire apache/logs de votre serveur. 

Il me semble que vous avez une installation locale de DigiRisk, dans ce cas la, vous le trouverez sans doute dans C:/EvariskServer/apache/logs/error.log

**Comment by FKACAPIC29** [comment]
[error.log](https://github.com/Evarisk/Digirisk/files/2720403/error.log)
![capture ecran](https://user-images.githubusercontent.com/24940570/50587435-39ce4b80-0e7e-11e9-9022-7b91562f75fc.PNG)

**Comment by eoxia-jimmy** [comment]
Peut être une solution à essayer:

Dans le fichier C:/EvariskServer/htdocs/Evarisk/wp-content/plugins/digirisk/modules/update_manager/update/update-7000.php

Remplacer les lignes 540 à 548 par:

```
if ( ! empty ( $document_meta['dateGeneration']['date_input'] ) && ! empty( $document_meta['dateGeneration']['date_input']['fr_FR'] ) && ! empty( $document_meta['dateGeneration']['date_input']['fr_FR']['date_time'] ) ) {
					$document_meta['dateGeneration'] = preg_replace('#(\d{2})/(\d{2})/(\d{4})\s(.*)#', '$3-$2-$1 $4', $document_meta['dateGeneration']['date_input']['fr_FR']['date_time'] );
				}
				if ( ! empty ( $document_meta['dateDebutAudit']['date_input'] ) && ! empty( $document_meta['dateDebutAudit']['date_input']['fr_FR'] ) && ! empty( $document_meta['dateDebutAudit']['date_input']['fr_FR']['date_time'] ) ) {
					$document_meta['dateDebutAudit'] = preg_replace('#(\d{2})/(\d{2})/(\d{4})\s(.*)#', '$3-$2-$1 $4', $document_meta['dateDebutAudit']['date_input']['fr_FR']['date_time'] );
				}
				if ( ! empty ( $document_meta['dateFinAudit']['date_input'] ) && ! empty( $document_meta['dateFinAudit']['date_input']['fr_FR'] ) && ! empty( $document_meta['dateFinAudit']['date_input']['fr_FR']['date_time'] ) ) {
					$document_meta['dateFinAudit'] = preg_replace('#(\d{2})/(\d{2})/(\d{4})\s(.*)#', '$3-$2-$1 $4', $document_meta['dateFinAudit']['date_input']['fr_FR']['date_time'] );
				}
```

Puis relancer la mise à jour des données de DigiRisk

**Comment by FKACAPIC29** [comment]
Pourriez-vous me faire parvenir le fichier update-7000.php mis à jour avec votre solution ?
Je n'ai pas d'éditeur pour réaliser la manipulation.

Par avance, merci

**Comment by eoxia-jimmy** [comment]
Je ne peux pas partager un fichier .php directement ici.

Donc voici un lien ou le fichier est accessible: https://gist.github.com/eoxia-jimmy/fe392194a19ab8b9889fb76189e3023b

Vous pouvez faire download ZIP en haut à gauche, puis l'extraire, le fichier se trouve dedans.

**Comment by FKACAPIC29** [comment]
Beau travail !
Merci

**Comment by FKACAPIC29** [comment]
Effectivement, j'ai réussi la mise à jour jusqu'au bout du processus mais dans l'affaire j'ai perdu l'historique des modifications, les utilisateurs, signalisations, fiches de poste.
A première vue, je ne dispose que de l'arboresence groupement/UT ...

Une solution pour récupérer le reste ?
