### ISSUE TITLE
Erreur lors generation document unique

### ISSUE THREAD

**Issue by nbriandvpf** [Evarisk/WP-Digirisk#8]
Bonjour, 

Nous avons depuis quelques semaines travailler sur la refonte de notre document unique. Du coup nous avons démarrer avec votre outil Evarisk, en version 5.1.9.5 .
Nous avons renseigné des unités de travail, des risques, des utilisateurs. Avant d'aller plus loin nous avons voulu générer le document unique. Mais lorsque l'on clique sur le bouton, yous recevons : 
"Le document unique n'a pas pu être sauvegardé".
Avons nous raté quelque chose ? Ou est-ce un bug ?

Merci d'avance,
Nicolas

**Comment by eoxia-alexandre** [comment]
Bonjour,

Il existe en effet un bug dans la version 5.X.X.X pour la corriger il vous faut effectuer la requête suivante

`ALTER TABLE wp_eva__ged_documents_document_unique CHANGE id_model id_model INT(10) UNSIGNED NULL DEFAULT '1' COMMENT 'The model used to generate the DUER';`

Cdlt,
Alexandre Techer

**Comment by nbriandvpf** [comment]
Un grand merci, ca fonctionne. 
Bonne journée,
Nicolas
