### ISSUE TITLE
Changer numéros/classement des Gp et UT 

### ISSUE THREAD

**Issue by Riskere** [Evarisk/WP-Digirisk#87]
Introduire la possibilité de modifier les numéros du GP et des UT pour un classement plus visuel (UT1, 2, 3, etc). Ainsi que la possibilité de classer les UT et GP (dans l'organisation).

**Comment by lmag** [comment]
Bonjour,
La notion UT1, 2, 3 etc... sont des références uniques et auto incrémentés. Si on permet leur changement comment trouver une unité de travail précise ?
Dans le cas de 3, 4, 5 poste d'accueil par exemple ?

**Comment by Riskere** [comment]
Je comprends l'utilité de l'auto incrémentation pour les grosses entreprises. 
Juste réinitialiser les numéros lors de la suppression d'un UT ou GP alors ? (pour recommencer au numéro GP1 ou UT1 au lieu de commencer à UT15 ou GP4 par exemple)

**Comment by lmag** [comment]
Il est difficile d'introduire une clé unique sur une UT ou un GP puis de changer le numéro unique par la suite.
Nous avions envisagé de mettre un numéro non consécutif comme AAMM-XYZ mais cela prend trop de place.
La numérotation unique permet aussi d'avoir la certitude de l'unité dont il est question en cas de problème juridique c'est plus simple que le "nom".
Nous avions aussi envisager une option pour masquer le numero et l'index afin de laisser que le titre...

**Comment by eoxia-jimmy** [comment]
@Riskere @lmag je relance cette conversation, aucune solution n'a été apportée il me semble. Le problème est-il toujours d'actualités ?

**Comment by lmag** [comment]
Oui pour le moment on laisse en l'état une solution serait de rajouter une option pour masquer les numero de GP et UT.
