### ISSUE TITLE
Aide à la migration de 5.1.9.5 vers 6.1

### ISSUE THREAD

**Issue by nbriandvpf** [Evarisk/WP-Digirisk#9]
Bonjour, 

Nous souhaitons migrer notre travail déjà effectué sur le version 5 de Evarisk, vers la dernière version 6 de Digirisk.
Nous n'avons pas trouver de guide qui nous indique la marche à suivre.
Avez vous une documentation qui nous aiderait ?

Merci d'avance,

**Comment by lmag** [comment]
Bonjour,

Nous n'avons pas éditer de guide pour le moment. Nous sommes en finalisation des scripts il devrait être livré dans la semaine, pour le moment ils sont désactivé dans le code.
Les migrations sont fonctionnelles si vous n'avez pas "bricoler" la base : 
-Pas de nouvelle méthode d'evaluation des  risques
-Pas de nouvelles catégories

La migration se fera lors l'installation de Digirisk automatiquement. Le mode d'emploi sera réduit il faudra bien penser aux sauvegardes :-)

**Comment by nbriandvpf** [comment]
Merci pour ce retour rapide.
Nous n'avons pas personnalisé les méthodes, ni les catégories. Cela devrait donc aller.
Je vais attendre la nouvelle mouture.

Cordialement

**Comment by lmag** [comment]
Oui dans ce cas cela devrait fonctionner

**Comment by nbriandvpf** [comment]
Bonjour, 

Est-ce que les scripts de migration sont maintenant disponibles ?
Merci

Bonne journée

**Comment by eoxia-alexandre** [comment]
Bonjour,

Oui les scripts de migration sont disponibles dans la version actuellement livré sur WordPress.org

**Comment by nbriandvpf** [comment]
Super Merci.
J'ai mis à jour ma version Windows via le système de gestion des extension, et suis donc maintenant en v6.2.0.2.
Par contre je ne mets pas la main sur un menu de migration de version. Pouvez vous me dire comment j'accède aux scripts de migration ?
Merci d'avance

**Comment by lmag** [comment]
1) Pensez aux sauvegardes dans un premier temps

Puis, Pour réaliser la migration il faut :  
Désactiver l'extension evarisk.
Puis activer l'extension Digirisk.
Ensuite cliquez sur Digirisk, il va lance la migration
A la fin tout est dans Digirisk, il ne faut plus reactiver evarisk.

Bonne soirée

**Comment by nbriandvpf** [comment]
Bonjour, 

Je pense que je ne dois pas être dans le bon cas : j'ai utilisé les versions packagés Windows. Je me trouve donc avec deux répertoires distincts : c:\Digirisk et C:\EvariskServer qui contient chacun le serveur web, sql, ...
Du coup je lance l'un ou l'autre, mais il ne se voit pas réciproquement.
Comment puis-je récupérer du dossier EvariskServer, la partie "module" que je pourrai donc glisser dans c:\Digirisk , pour essayer cette migration ?

**Comment by nbriandvpf** [comment]
Ne tenez pas compte de mon précédent message. 

J'ai finalement pu trouver comment faire. Voila ce que j'ai fait :
- Lancer la version Evarisk
- dans le module Extension, j'ai ajouter une extension
- Chercher **Digirisk** comme extension à ajouter
Ensuite j'ai pu réaliser la migration comme vous l'avez décrite :
- Désactiver l'extension evarisk.
- Puis activer l'extension Digirisk.
- Ensuite cliquez sur Digirisk, il va lance la migration

En tout cas merci pour votre aide.
