### ISSUE TITLE
Gestion des droits

### ISSUE THREAD

**Issue by antoineb33000** [Evarisk/WP-Digirisk#99]
A priori la gestion des droits autorise toujours les causeries

**Comment by antoineb33000** [comment]
La gestion de ne prend pas en compte :
La case DU simple, il faut que la case tous soit cochée

**Comment by antoineb33000** [comment]
La case "tous" peut restée cochée alors que les autres cases sont décochées

**Comment by lmag** [comment]
Bonjour,
On a bien pris ce point en compte en #2425 pour votre suivi

**Comment by lmag** [comment]
On a prévu une livraison milieu de semaine prochaine

**Comment by nicolas-eoxia** [comment]
Fix de la case Tous 
![animiertes-gif-von-online-umwandeln-de (1)](https://user-images.githubusercontent.com/52404047/76631208-92e54500-6541-11ea-9edb-9c1f98d9c88f.gif)

**Comment by nicolas-eoxia** [comment]
Fix droit : La case DU peut maintenant être la seule case coché
![GIFMaker org_eq1VHR](https://user-images.githubusercontent.com/52404047/76633651-574c7a00-6545-11ea-9932-ca04e39c6d2f.gif)
